---
# make ansible play nice in a virtualenv
ansible_python_interpreter: python

provider:
  host: "{{ inventory_hostname }}"
  username: admin
  password: admin
  authorize: yes
  transport: cli

eos_purge_vlan_trunk_groups: yes

eos_users:
  name: cvpadmin
  encryption: md5
  passwd: '$1$yRC6xbP/$gXhY/i6gFlbBJM.q67Pu2.'
  privilege: 15
  role: network-admin

gateway:
   gateway: '10.132.0.1'

mgmt:
   spine01:
      hostname: spine01
      loopback0_ip: "10.1.0.101 255.255.255.255"
   spine02:
      hostname: spine02
      loopback0_ip: "10.2.0.102 255.255.255.255"
   spine03:
      hostname: spine03
      loopback0_ip: "10.3.0.103 255.255.255.255"
   spine04:
      hostname: spine04
      loopback0_ip: "10.4.0.104 255.255.255.255"
   leaf01:
      hostname: leaf01
      loopback0_ip: "10.5.0.201 255.255.255.255"
   leaf02:
      hostname: leaf02
      loopback0_ip: "10.6.0.202 255.255.255.255"
   leaf03:
      hostname: leaf03
      loopback0_ip: "10.7.0.203 255.255.255.255"
   leaf04:
      hostname: leaf04
      loopback0_ip: "10.8.0.204 255.255.255.255"
   leaf05:
      hostname: leaf05
      loopback0_ip: "10.9.0.205 255.255.255.255"
   leaf06:
      hostname: leaf06
      loopback0_ip: "10.10.0.206 255.255.255.255"
#
#
# ebgp fabric
#
#
fabric:
    spine01:
        asn: 65020
        rid: 10.10.2.1
        fabricpeers:
            "10.0.0.1 remote-as 65011":
            "10.0.0.17 remote-as 65012":
            "10.0.0.33 remote-as 65013":
            "10.0.0.49 remote-as 65014":
            "10.0.0.65 remote-as 65015":
            "10.0.0.81 remote-as 65016":
        networks:
            "10.0.0.0 mask 255.255.255.252":
            "10.0.0.16 mask 255.255.255.252":
            "10.0.0.32 mask 255.255.255.252":
            "10.0.0.48 mask 255.255.255.252":
            "10.0.0.64 mask 255.255.255.252":
            "10.0.0.80 mask 255.255.255.252":
    spine02:
        asn: 65020
        rid: 10.10.2.2
        fabricpeers:
            "10.0.0.5 remote-as 65011":
            "10.0.0.21 remote-as 65012":
            "10.0.0.37 remote-as 65013":
            "10.0.0.53 remote-as 65014":
            "10.0.0.69 remote-as 65015":
            "10.0.0.85 remote-as 65016":
        networks:
            "10.0.0.4 mask 255.255.255.252":
            "10.0.0.20 mask 255.255.255.252":
            "10.0.0.36 mask 255.255.255.252":
            "10.0.0.52 mask 255.255.255.252":
            "10.0.0.68 mask 255.255.255.252":
            "10.0.0.84 mask 255.255.255.252":
    spine03:
        asn: 65020
        rid: 10.10.2.3
        fabricpeers:
            "10.0.0.9 remote-as 65011":
            "10.0.0.25 remote-as 65012":
            "10.0.0.41 remote-as 65013":
            "10.0.0.57 remote-as 65014":
            "10.0.0.73 remote-as 65015":
            "10.0.0.89 remote-as 65016":
        networks:
            "10.0.0.8 mask 255.255.255.252":
            "10.0.0.24 mask 255.255.255.252":
            "10.0.0.40 mask 255.255.255.252":
            "10.0.0.56 mask 255.255.255.252":
            "10.0.0.72 mask 255.255.255.252":
            "10.0.0.88 mask 255.255.255.252":
    spine04:
        asn: 65020
        rid: 10.10.2.4
        fabricpeers:
            "10.0.0.13 remote-as 65011":
            "10.0.0.29 remote-as 65012":
            "10.0.0.45 remote-as 65013":
            "10.0.0.61 remote-as 65014":
            "10.0.0.77 remote-as 65015":
            "10.0.0.93 remote-as 65016":
        networks:
            "10.0.0.12 mask 255.255.255.252":
            "10.0.0.28 mask 255.255.255.252":
            "10.0.0.44 mask 255.255.255.252":
            "10.0.0.60 mask 255.255.255.252":
            "10.0.0.76 mask 255.255.255.252":
            "10.0.0.94 mask 255.255.255.252":
    leaf01:
        asn: 65011
        rid: 10.10.1.1
        fabricpeers:
            "10.0.0.2 remote-as 65020":
            "10.0.0.6 remote-as 65020":
            "10.0.0.10 remote-as 65020":
            "10.0.0.14 remote-as 65020":
        networks:
            "10.0.0.0 mask 255.255.255.252":
            "10.0.0.4 mask 255.255.255.252":
            "10.0.0.8 mask 255.255.255.252":
            "10.0.0.12 mask 255.255.255.252":
    leaf02:
        asn: 65012
        rid: 10.10.1.2
        fabricpeers:
            "10.0.0.18 remote-as 65020":
            "10.0.0.22 remote-as 65020":
            "10.0.0.26 remote-as 65020":
            "10.0.0.30 remote-as 65020":
        networks:
            "10.0.0.16 mask 255.255.255.252":
            "10.0.0.20 mask 255.255.255.252":
            "10.0.0.24 mask 255.255.255.252":
            "10.0.0.28 mask 255.255.255.252":
    leaf03:
        asn: 65013
        rid: 10.10.1.3
        fabricpeers:
            "10.0.0.34 remote-as 65020":
            "10.0.0.38 remote-as 65020":
            "10.0.0.42 remote-as 65020":
            "10.0.0.46 remote-as 65020":
        networks:
            "10.0.0.32 mask 255.255.255.252":
            "10.0.0.36 mask 255.255.255.252":
            "10.0.0.40 mask 255.255.255.252":
            "10.0.0.44 mask 255.255.255.252":
    leaf04:
        asn: 65014
        rid: 10.10.1.4
        fabricpeers:
            "10.0.0.50 remote-as 65020":
            "10.0.0.54 remote-as 65020":
            "10.0.0.58 remote-as 65020":
            "10.0.0.62 remote-as 65020":
        networks:
            "10.0.0.48 mask 255.255.255.252":
            "10.0.0.52 mask 255.255.255.252":
            "10.0.0.56 mask 255.255.255.252":
            "10.0.0.60 mask 255.255.255.252":
    leaf05:
        asn: 65015
        rid: 10.10.1.5
        fabricpeers:
            "10.0.0.66 remote-as 65020":
            "10.0.0.70 remote-as 65020":
            "10.0.0.74 remote-as 65020":
            "10.0.0.78 remote-as 65020":
        networks:
            "10.0.0.64 mask 255.255.255.252":
            "10.0.0.68 mask 255.255.255.252":
            "10.0.0.72 mask 255.255.255.252":
            "10.0.0.76 mask 255.255.255.252":
    leaf06:
        asn: 65016
        rid: 10.10.1.6
        fabricpeers:
            "10.0.0.82 remote-as 65020":
            "10.0.0.86 remote-as 65020":
            "10.0.0.90 remote-as 65020":
            "10.0.0.94 remote-as 65020":
        networks:
            "10.0.0.80 mask 255.255.255.252":
            "10.0.0.84 mask 255.255.255.252":
            "10.0.0.88 mask 255.255.255.252":
            "10.0.0.92 mask 255.255.255.252":
#
#
# ospf fabric
#
#

ospf:
  spine01:
     process: '1'
     router_id: '10.10.2.1'
     networks:
        '10.0.0.0/30':
        '10.0.0.16/30':
        '10.0.0.32/30':
        '10.0.0.48/30':
        '10.0.0.64/30':
        '10.0.0.80/30':
  spine02:
     process: '1'
     router_id: '10.10.2.2'
     networks:
        '10.0.0.4/30':
        '10.0.0.20/30':
        '10.0.0.36/30':
        '10.0.0.52/30':
        '10.0.0.68/30':
        '10.0.0.84/30':
  spine03:
     process: '1'
     router_id: '10.10.2.3'
     networks:
        '10.0.0.8/30':
        '10.0.0.24/30':
        '10.0.0.40/30':
        '10.0.0.56/30':
        '10.0.0.72/30':
        '10.0.0.88/30':
  spine04:
     process: '1'
     router_id: '10.10.2.4'
     networks:
        '10.0.0.12/30':
        '10.0.0.28/30':
        '10.0.0.44/30':
        '10.0.0.60/30':
        '10.0.0.76/30':
        '10.0.0.92/30':
  leaf01:
     process: '1'
     router_id: '10.10.1.1'
     networks:
        '10.0.0.0/30':
        '10.0.0.4/30':
        '10.0.0.8/30':
        '10.0.0.12/30':
  leaf02:
     process: '1'
     router_id: '10.10.1.2'
     networks:
        '10.0.0.16/30':
        '10.0.0.20/30':
        '10.0.0.24/30':
        '10.0.0.28/30':
  leaf03:
     process: '1'
     router_id: '10.10.1.3'
     networks:
        '10.0.0.32/30':
        '10.0.0.36/30':
        '10.0.0.40/30':
        '10.0.0.44/30':
  leaf04:
     process: '1'
     router_id: '10.10.1.4'
     networks:
        '10.0.0.48/30':
        '10.0.0.52/30':
        '10.0.0.56/30':
        '10.0.0.60/30':
  leaf05:
     process: '1'
     router_id: '10.10.1.5'
     networks:
        '10.0.0.64/30':
        '10.0.0.68/30':
        '10.0.0.72/30':
        '10.0.0.76/30':
  leaf06:
     process: '1'
     router_id: '10.10.1.6'
     networks:
        '10.0.0.80/30':
        '10.0.0.84/30':
        '10.0.0.88/30':
        '10.0.0.92/30':

# interfaces
interface:
   spine01:
      Ethernet 1:
         ipv4: "10.0.0.2"
      Ethernet 2:
         ipv4: "10.0.0.18"
      Ethernet 3:
          ipv4: "10.0.0.34"
      Ethernet 4:
          ipv4: "10.0.0.50"
      Ethernet 5:
          ipv4: "10.0.0.66"
      Ethernet 6:
          ipv4: "10.0.0.82"
   spine02:
        Ethernet 1:
            ipv4: "10.0.0.6"
        Ethernet 2:
            ipv4: "10.0.0.22"
        Ethernet 3:
            ipv4: "10.0.0.38"
        Ethernet 4:
            ipv4: "10.0.0.54"
        Ethernet 5:
            ipv4: "10.0.0.70"
        Ethernet 6:
            ipv4: "10.0.0.86"
   spine03:
        Ethernet 1:
            ipv4: "10.0.0.10"
        Ethernet 2:
            ipv4: "10.0.0.26"
        Ethernet 3:
            ipv4: "10.0.0.42"
        Ethernet 4:
            ipv4: "10.0.0.58"
        Ethernet 5:
            ipv4: "10.0.0.74"
        Ethernet 6:
            ipv4: "10.0.0.90"
   spine04:
        Ethernet 1:
            ipv4: "10.0.0.14"
        Ethernet 2:
            ipv4: "10.0.0.30"
        Ethernet 3:
            ipv4: "10.0.0.46"
        Ethernet 4:
            ipv4: "10.0.0.62"
        Ethernet 5:
            ipv4: "10.0.0.78"
        Ethernet 6:
            ipv4: "10.0.0.94"
   leaf01:
        Ethernet 1:
            ipv4: "10.0.0.1"
        Ethernet 2:
            ipv4: "10.0.0.5"
        Ethernet 3:
            ipv4: "10.0.0.9"
        Ethernet 4:
            ipv4: "10.0.0.13"
   leaf02:
        Ethernet 1:
            ipv4: "10.0.0.17"
        Ethernet 2:
            ipv4: "10.0.0.21"
        Ethernet 3:
            ipv4: "10.0.0.25"
        Ethernet 4:
            ipv4: "10.0.0.29"
   leaf03:
        Ethernet 1:
            ipv4: "10.0.0.33"
        Ethernet 2:
            ipv4: "10.0.0.37"
        Ethernet 3:
            ipv4: "10.0.0.41"
        Ethernet 4:
            ipv4: "10.0.0.45"
   leaf04:
        Ethernet 1:
            ipv4: "10.0.0.49"
        Ethernet 2:
            ipv4: "10.0.0.53"
        Ethernet 3:
            ipv4: "10.0.0.57"
        Ethernet 4:
            ipv4: "10.0.0.61"
   leaf05:
        Ethernet 1:
            ipv4: "10.0.0.65"
        Ethernet 2:
            ipv4: "10.0.0.69"
        Ethernet 3:
            ipv4: "10.0.0.73"
        Ethernet 4:
            ipv4: "10.0.0.77"
   leaf06:
        Ethernet 1:
            ipv4: "10.0.0.81"
        Ethernet 2:
            ipv4: "10.0.0.85"
        Ethernet 3:
            ipv4: "10.0.0.89"
        Ethernet 4:
            ipv4: "10.0.0.93"
# vlans on the leafs
vlan:
    leaf01:
        10:
            name: "application10"
        20:
            name: "application20"
        30:
            name: "application30"
        40:
            name: "application40"
    leaf02:
        10:
            name: "application10"
        20:
            name: "application20"
        30:
            name: "application30"
        40:
            name: "application40"
    leaf03:
        10:
            name: "application10"
        20:
            name: "application20"
        30:
            name: "application30"
        40:
            name: "application40"
    leaf04:
        10:
            name: "application10"
        20:
            name: "application20"
        30:
            name: "application30"
        40:
            name: "application40"
    leaf05:
        10:
            name: "application10"
        20:
            name: "application20"
        30:
            name: "application30"
        40:
            name: "application40"
    leaf06:
        10:
            name: "application10"
        20:
            name: "application20"
        30:
            name: "application30"
        40:
            name: "application40"
